apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-krish-deploy
  labels:
    app: bankapp-krish-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-krish-app
  template:
    metadata:
      labels:
        app: bankapp-krish-app
    spec:
      containers:
      - name: bankapp-krish-container
        image: bvky/bankapp-krishna:v2.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-krish-np-service
  labels:
    app: bankapp-krish-app
spec:
  selector:
    app: bankapp-krish-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
	
	
	
	
	
	
